import { Box, Container, Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../components/About";
import { Bottom } from "../components/Bottom";
import { Header } from "../components/Header";
import { Jobs } from "../components/Jobs";
import { Partners } from "../components/Partners";
import { Projects } from "../components/Projects";

const Home: NextPage = () => {
  return (
    <>
      <Container maxW="1440px" mb="96px">
        <Head>
          <title>Kedoo Labs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <Box>
          <About />
          <Projects />
          <Partners />
          <Jobs />
        </Box>
      </Container>

      <Bottom />
    </>
  );
};

export default Home;
